import math

def get_animation():
    return [
        [
            ('mixamorigRightHandIndex1', 'z', math.pi/4.5),
            ('mixamorigRightHandIndex2', 'z', math.pi/4.5),
            ('mixamorigRightHandIndex3', 'z', math.pi/4.5),
            ('mixamorigRightHandMiddle1', 'z', math.pi/4.5),
            ('mixamorigRightHandMiddle2', 'z', math.pi/4.5),
            ('mixamorigRightHandMiddle3', 'z', math.pi/4.5),
            ('mixamorigRightHandRing1', 'z', math.pi/4.5),
            ('mixamorigRightHandRing2', 'z', math.pi/4.5),
            ('mixamorigRightHandRing3', 'z', math.pi/4.5),
            ('mixamorigRightHandPinky1', 'z', math.pi/4.5),
            ('mixamorigRightHandPinky2', 'z', math.pi/4.5),
            ('mixamorigRightHandPinky3', 'z', math.pi/4.5),
            ('mixamorigRightHandThumb1', 'x', math.pi/3),
            ('mixamorigRightHandThumb1', 'y', math.pi/3),
            ('mixamorigRightHandThumb2', 'y', -math.pi/6),
            ('mixamorigRightHandThumb3', 'y', -math.pi/7),
            ('mixamorigRightHand', 'z', -math.pi/10),
            ('mixamorigRightHand', 'y', math.pi/4),
            ('mixamorigRightForeArm', 'z', math.pi/9),
            ('mixamorigRightForeArm', 'x', math.pi/18),
            ('mixamorigRightArm', 'x', -math.pi/6.5),
        ],
        [
            ('mixamorigRightHandIndex1', 'z', 0),
            ('mixamorigRightHandIndex2', 'z', 0),
            ('mixamorigRightHandIndex3', 'z', 0),
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb1', 'x', 0),
            ('mixamorigRightHandThumb1', 'y', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightHand', 'y', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightForeArm', 'x', 0),
            ('mixamorigRightArm', 'x', 0),
        ],
    ]
