import math

def get_animation():
    return [
        [
            ('mixamorigLeftHandIndex1', 'y', -math.pi/9),
            ('mixamorigLeftHandMiddle1', 'y', -math.pi/18),
            ('mixamorigLeftHandRing1', 'y', math.pi/18),
            ('mixamorigLeftHandPinky1', 'y', math.pi/9),
            ('mixamorigLeftHand', 'x', math.pi/2),
            ('mixamorigLeftHand', 'z', math.pi/6),
            ('mixamorigLeftHand', 'y', math.pi/9),
            ('mixamorigLeftForeArm', 'x', math.pi/9),
            ('mixamorigLeftArm', 'y', -math.pi/12),
            ('mixamorigRightHandMiddle1', 'z', math.pi/2),
            ('mixamorigRightHandMiddle2', 'z', math.pi/2),
            ('mixamorigRightHandMiddle3', 'z', math.pi/2),
            ('mixamorigRightHandRing1', 'z', math.pi/2),
            ('mixamorigRightHandRing2', 'z', math.pi/2),
            ('mixamorigRightHandRing3', 'z', math.pi/2),
            ('mixamorigRightHandPinky1', 'z', math.pi/2),
            ('mixamorigRightHandPinky2', 'z', math.pi/2),
            ('mixamorigRightHandPinky3', 'z', math.pi/2),
            ('mixamorigRightHandPinky1', 'z', math.pi/2),
            ('mixamorigRightHandPinky2', 'z', math.pi/2),
            ('mixamorigRightHandPinky3', 'z', math.pi/2),
            ('mixamorigRightHandThumb2', 'y', -math.pi/2.5),
            ('mixamorigRightHandThumb3', 'y', -math.pi/2.5),
            ('mixamorigRightHand', 'x', -math.pi/2),
            ('mixamorigRightHand', 'z', math.pi/12),
            ('mixamorigRightForeArm', 'z', math.pi/6),
            ('mixamorigRightForeArm', 'x', -math.pi/36),
            ('mixamorigRightArm', 'x', -math.pi/15),
        ],
        [
            ('mixamorigLeftHandIndex1', 'y', 0),
            ('mixamorigLeftHandMiddle1', 'y', 0),
            ('mixamorigLeftHandRing1', 'y', 0),
            ('mixamorigLeftHandPinky1', 'y', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftHand', 'z', 0),
            ('mixamorigLeftHand', 'y', 0),
            ('mixamorigLeftForeArm', 'x', 0),
            ('mixamorigLeftArm', 'y', 0),
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightForeArm', 'x', 0),
            ('mixamorigRightArm', 'x', 0),
        ],
    ]
