import math

def get_animation():
    return [
        [
            ('mixamorigRightHandIndex1', 'z', math.pi/2),
            ('mixamorigRightHandIndex2', 'z', math.pi/2),
            ('mixamorigRightHandIndex3', 'z', math.pi/2),
            ('mixamorigRightHandMiddle1', 'z', math.pi/2),
            ('mixamorigRightHandMiddle2', 'z', math.pi/2),
            ('mixamorigRightHandMiddle3', 'z', math.pi/2),
            ('mixamorigRightHandRing1', 'z', math.pi/2),
            ('mixamorigRightHandRing2', 'z', math.pi/2),
            ('mixamorigRightHandRing3', 'z', math.pi/2),
            ('mixamorigRightHandPinky1', 'z', math.pi/2),
            ('mixamorigRightHandPinky2', 'z', math.pi/2),
            ('mixamorigRightHandPinky3', 'z', math.pi/2),
            ('mixamorigRightHandThumb1', 'x', math.pi/3),
            ('mixamorigRightHand', 'x', -math.pi/2),
            ('mixamorigRightHand', 'z', math.pi/9),
            ('mixamorigRightHand', 'y', -math.pi/18),
            ('mixamorigRightForeArm', 'z', math.pi/6),
            ('mixamorigRightForeArm', 'x', math.pi/12),
            ('mixamorigRightArm', 'x', -math.pi/3.5),
            ('mixamorigRightArm', 'y', math.pi/12),
            ('mixamorigLeftHandIndex1', 'z', -math.pi/2),
            ('mixamorigLeftHandIndex2', 'z', -math.pi/2),
            ('mixamorigLeftHandIndex3', 'z', -math.pi/2),
            ('mixamorigLeftHandMiddle1', 'z', -math.pi/2),
            ('mixamorigLeftHandMiddle2', 'z', -math.pi/2),
            ('mixamorigLeftHandMiddle3', 'z', -math.pi/2),
            ('mixamorigLeftHandRing1', 'z', -math.pi/2),
            ('mixamorigLeftHandRing2', 'z', -math.pi/2),
            ('mixamorigLeftHandRing3', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky1', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky2', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky3', 'z', -math.pi/2),
            ('mixamorigLeftHandThumb1', 'x', math.pi/3),
            ('mixamorigLeftHand', 'x', -math.pi/2.5),
            ('mixamorigLeftHand', 'z', -math.pi/9),
            ('mixamorigLeftHand', 'y', math.pi/18),
            ('mixamorigLeftForeArm', 'z', -math.pi/6),
            ('mixamorigLeftForeArm', 'x', math.pi/12),
            ('mixamorigLeftArm', 'x', -math.pi/6),
            ('mixamorigLeftArm', 'y', -math.pi/12),
        ],
        [
            ('mixamorigRightHandIndex1', 'z', 0),
            ('mixamorigRightHandIndex2', 'z', 0),
            ('mixamorigRightHandIndex3', 'z', 0),
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb1', 'x', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightHand', 'y', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightForeArm', 'x', 0),
            ('mixamorigRightArm', 'x', 0),
            ('mixamorigRightArm', 'y', 0),
            ('mixamorigLeftHandIndex1', 'z', 0),
            ('mixamorigLeftHandIndex2', 'z', 0),
            ('mixamorigLeftHandIndex3', 'z', 0),
            ('mixamorigLeftHandMiddle1', 'z', 0),
            ('mixamorigLeftHandMiddle2', 'z', 0),
            ('mixamorigLeftHandMiddle3', 'z', 0),
            ('mixamorigLeftHandRing1', 'z', 0),
            ('mixamorigLeftHandRing2', 'z', 0),
            ('mixamorigLeftHandRing3', 'z', 0),
            ('mixamorigLeftHandPinky1', 'z', 0),
            ('mixamorigLeftHandPinky2', 'z', 0),
            ('mixamorigLeftHandPinky3', 'z', 0),
            ('mixamorigLeftHandThumb1', 'x', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftHand', 'z', 0),
            ('mixamorigLeftHand', 'y', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftForeArm', 'x', 0),
            ('mixamorigLeftArm', 'x', 0),
            ('mixamorigLeftArm', 'y', 0),
        ],
    ]
