import math

def get_animation():
    return [
        [
            ('mixamorigRightHandMiddle1', 'z', math.pi/1.5),
            ('mixamorigRightHandMiddle2', 'z', math.pi/2),
            ('mixamorigRightHandMiddle3', 'z', math.pi/2),
            ('mixamorigRightHandRing1', 'z', math.pi/1.5),
            ('mixamorigRightHandRing2', 'z', math.pi/2),
            ('mixamorigRightHandRing3', 'z', math.pi/2),
            ('mixamorigRightHandPinky1', 'z', math.pi/1.5),
            ('mixamorigRightHandPinky2', 'z', math.pi/2),
            ('mixamorigRightHandPinky3', 'z', math.pi/2),
            ('mixamorigRightHandThumb1', 'x', math.pi/3),
            ('mixamorigRightHandThumb1', 'z', math.pi/2),
            ('mixamorigRightHand', 'y', -math.pi/5),
            ('mixamorigRightHand', 'z', math.pi/6),
            ('mixamorigRightArm', 'y', math.pi/6),
            ('mixamorigRightArm', 'x', -math.pi/36),
            ('mixamorigLeftHandMiddle1', 'z', -math.pi/2),
            ('mixamorigLeftHandMiddle2', 'z', -math.pi/2),
            ('mixamorigLeftHandMiddle3', 'z', -math.pi/2),
            ('mixamorigLeftHandRing1', 'z', -math.pi/2),
            ('mixamorigLeftHandRing2', 'z', -math.pi/2),
            ('mixamorigLeftHandRing3', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky1', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky2', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky3', 'z', -math.pi/2),
            ('mixamorigLeftHandThumb1', 'y', -math.pi/2),
            ('mixamorigLeftForeArm', 'z', -math.pi/3.7),
            ('mixamorigLeftForeArm', 'x', -math.pi/6),
            ('mixamorigLeftArm', 'z', -math.pi/2.4),
            ('mixamorigLeftHand', 'z', -math.pi/7),
            ('mixamorigLeftHand', 'x', -math.pi/3),
            ('mixamorigLeftHand', 'y', math.pi/12),
        ],
        [
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb1', 'x', 0),
            ('mixamorigRightHandThumb1', 'z', 0),
            ('mixamorigRightHand', 'y', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightArm', 'y', 0),
            ('mixamorigRightArm', 'x', 0),
            ('mixamorigLeftHandMiddle1', 'z', 0),
            ('mixamorigLeftHandMiddle2', 'z', 0),
            ('mixamorigLeftHandMiddle3', 'z', 0),
            ('mixamorigLeftHandRing1', 'z', 0),
            ('mixamorigLeftHandRing2', 'z', 0),
            ('mixamorigLeftHandRing3', 'z', 0),
            ('mixamorigLeftHandPinky1', 'z', 0),
            ('mixamorigLeftHandPinky2', 'z', 0),
            ('mixamorigLeftHandPinky3', 'z', 0),
            ('mixamorigLeftHandThumb1', 'y', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftForeArm', 'x', 0),
            ('mixamorigLeftArm', 'z', -1.0471975511965976),
            ('mixamorigLeftHand', 'z', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftHand', 'y', 0),
        ],
    ]
