import math

def get_animation():
    return [
        [
            ('mixamorigRightHandIndex2', 'z', math.pi/4.2),
            ('mixamorigRightHandIndex3', 'z', math.pi/4.2),
            ('mixamorigRightHandMiddle1', 'z', math.pi/1.5),
            ('mixamorigRightHandMiddle2', 'z', math.pi/1.5),
            ('mixamorigRightHandMiddle3', 'z', math.pi/1.5),
            ('mixamorigRightHandRing1', 'z', math.pi/1.6),
            ('mixamorigRightHandRing2', 'z', math.pi/1.6),
            ('mixamorigRightHandRing3', 'z', math.pi/1.6),
            ('mixamorigRightHandPinky1', 'z', math.pi/1.8),
            ('mixamorigRightHandPinky2', 'z', math.pi/1.8),
            ('mixamorigRightHandPinky3', 'z', math.pi/1.8),
            ('mixamorigRightHandThumb1', 'x', math.pi/2.3),
            ('mixamorigRightHandThumb1', 'y', -math.pi/25),
            ('mixamorigRightHandThumb2', 'y', -math.pi/10),
            ('mixamorigRightHandThumb3', 'y', -math.pi/10),
            ('mixamorigRightHand', 'z', -math.pi/4),
            ('mixamorigRightForeArm', 'z', math.pi/5.3),
            ('mixamorigRightForeArm', 'x', math.pi/18),
            ('mixamorigRightArm', 'z', math.pi/2.4),
            ('mixamorigLeftHandIndex1', 'z', -math.pi/3),
            ('mixamorigLeftHandIndex2', 'z', -math.pi/3),
            ('mixamorigLeftHandIndex3', 'z', -math.pi/3),
            ('mixamorigLeftHandThumb1', 'x', math.pi/10),
            ('mixamorigLeftHandThumb2', 'y', math.pi/10),
            ('mixamorigLeftHand', 'y', math.pi/2.8),
            ('mixamorigLeftHand', 'x', math.pi/3),
            ('mixamorigLeftForeArm', 'z', -math.pi/6),
            ('mixamorigLeftForeArm', 'x', math.pi/18),
            ('mixamorigLeftArm', 'y', -math.pi/33),
            ('mixamorigLeftArm', 'z', -math.pi/2.4),
            ('mixamorigLeftArm', 'x', -math.pi/8.3),
        ],
        [
            ('mixamorigRightHandIndex2', 'z', 0),
            ('mixamorigRightHandIndex3', 'z', 0),
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb1', 'x', 0),
            ('mixamorigRightHandThumb1', 'y', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightForeArm', 'x', 0),
            ('mixamorigRightArm', 'z', 1.0471975511965976),
            ('mixamorigLeftHandIndex1', 'z', 0),
            ('mixamorigLeftHandIndex2', 'z', 0),
            ('mixamorigLeftHandIndex3', 'z', 0),
            ('mixamorigLeftHandThumb1', 'x', 0),
            ('mixamorigLeftHandThumb2', 'y', 0),
            ('mixamorigLeftHand', 'y', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftForeArm', 'x', 0),
            ('mixamorigLeftArm', 'y', 0),
            ('mixamorigLeftArm', 'z', -1.0471975511965976),
            ('mixamorigLeftArm', 'x', 0),
        ],
    ]
