import math

def get_animation():
    return [
        [
            ('mixamorigRightHandIndex1', 'y', math.pi/16),
            ('mixamorigRightHandRing1', 'y', -math.pi/12),
            ('mixamorigRightHandPinky1', 'y', -math.pi/8),
            ('mixamorigRightHandThumb1', 'y', math.pi/5),
            ('mixamorigRightHandThumb2', 'z', -math.pi/6),
            ('mixamorigRightHandThumb3', 'y', math.pi/6),
            ('mixamorigRightHand', 'x', -math.pi/6),
            ('mixamorigRightForeArm', 'z', math.pi/6),
            ('mixamorigRightArm', 'z', math.pi/2.4),
            ('mixamorigLeftHandIndex1', 'y', -math.pi/16),
            ('mixamorigLeftHandRing1', 'y', math.pi/8),
            ('mixamorigLeftHandPinky1', 'y', math.pi/8),
            ('mixamorigLeftHandThumb1', 'y', -math.pi/5),
            ('mixamorigLeftHandThumb2', 'z', math.pi/6),
            ('mixamorigLeftHandThumb3', 'y', -math.pi/6),
            ('mixamorigLeftHand', 'y', -math.pi/24),
            ('mixamorigLeftHand', 'x', -math.pi/6),
            ('mixamorigLeftForeArm', 'z', -math.pi/6),
            ('mixamorigLeftArm', 'z', -math.pi/2.4),
        ],
        [
            ('mixamorigRightHandIndex1', 'y', 0),
            ('mixamorigRightHandRing1', 'y', 0),
            ('mixamorigRightHandPinky1', 'y', 0),
            ('mixamorigRightHandThumb1', 'y', 0),
            ('mixamorigRightHandThumb2', 'z', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightArm', 'z', 1.0471975511965976),
            ('mixamorigLeftHandIndex1', 'y', 0),
            ('mixamorigLeftHandRing1', 'y', 0),
            ('mixamorigLeftHandPinky1', 'y', 0),
            ('mixamorigLeftHandThumb1', 'y', 0),
            ('mixamorigLeftHandThumb2', 'z', 0),
            ('mixamorigLeftHandThumb3', 'y', 0),
            ('mixamorigLeftHand', 'y', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftArm', 'z', -1.0471975511965976),
        ],
    ]
