import math

def get_animation():
    return [
        [
            ('mixamorigRightHandMiddle1', 'z', math.pi/1.5),
            ('mixamorigRightHandMiddle2', 'z', math.pi/1.5),
            ('mixamorigRightHandMiddle3', 'z', math.pi/1.5),
            ('mixamorigRightHandRing1', 'z', math.pi/1.6),
            ('mixamorigRightHandRing2', 'z', math.pi/1.6),
            ('mixamorigRightHandRing3', 'z', math.pi/1.6),
            ('mixamorigRightHandPinky1', 'z', math.pi/1.8),
            ('mixamorigRightHandPinky2', 'z', math.pi/1.8),
            ('mixamorigRightHandPinky3', 'z', math.pi/1.8),
            ('mixamorigRightHandThumb2', 'y', -math.pi/2.5),
            ('mixamorigRightHandThumb3', 'y', -math.pi/2.5),
            ('mixamorigRightHand', 'z', +math.pi/2.5),
            ('mixamorigRightHand', 'x', -math.pi/8),
            ('mixamorigRightForeArm', 'z', math.pi/15),
            ('mixamorigRightForeArm', 'x', -math.pi/10),
            ('mixamorigRightArm', 'y', math.pi/33),
            ('mixamorigRightArm', 'z', math.pi/2.2),
            ('mixamorigLeftHandMiddle1', 'z', -math.pi/1.5),
            ('mixamorigLeftHandMiddle2', 'z', -math.pi/1.5),
            ('mixamorigLeftHandMiddle3', 'z', -math.pi/1.5),
            ('mixamorigLeftHandRing1', 'z', -math.pi/1.6),
            ('mixamorigLeftHandRing2', 'z', -math.pi/1.6),
            ('mixamorigLeftHandRing3', 'z', -math.pi/1.6),
            ('mixamorigLeftHandPinky1', 'z', -math.pi/1.8),
            ('mixamorigLeftHandPinky2', 'z', -math.pi/1.8),
            ('mixamorigLeftHandPinky3', 'z', -math.pi/1.8),
            ('mixamorigLeftHandThumb1', 'y', -math.pi/4),
            ('mixamorigLeftHand', 'y', math.pi/2),
            ('mixamorigLeftHand', 'x', math.pi/2),
            ('mixamorigLeftForeArm', 'z', -math.pi/3.5),
            ('mixamorigLeftArm', 'x', -math.pi/5),
            ('mixamorigLeftArm', 'z', -math.pi/2.2),
        ],
        [
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightForeArm', 'x', 0),
            ('mixamorigRightArm', 'y', 0),
            ('mixamorigRightArm', 'z', 1.0471975511965976),
            ('mixamorigLeftHandMiddle1', 'z', 0),
            ('mixamorigLeftHandMiddle2', 'z', 0),
            ('mixamorigLeftHandMiddle3', 'z', 0),
            ('mixamorigLeftHandRing1', 'z', 0),
            ('mixamorigLeftHandRing2', 'z', 0),
            ('mixamorigLeftHandRing3', 'z', 0),
            ('mixamorigLeftHandPinky1', 'z', 0),
            ('mixamorigLeftHandPinky2', 'z', 0),
            ('mixamorigLeftHandPinky3', 'z', 0),
            ('mixamorigLeftHandThumb1', 'y', 0),
            ('mixamorigLeftHand', 'y', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftArm', 'x', 0),
            ('mixamorigLeftArm', 'z', -1.0471975511965976),
        ],
    ]
