import math

def get_animation():
    return [
        [
            ('mixamorigRightHandRing1', 'z', math.pi/2),
            ('mixamorigRightHandRing2', 'z', math.pi/2),
            ('mixamorigRightHandRing3', 'z', math.pi/2),
            ('mixamorigRightHandPinky1', 'z', math.pi/2),
            ('mixamorigRightHandPinky2', 'z', math.pi/2),
            ('mixamorigRightHandPinky3', 'z', math.pi/2),
            ('mixamorigRightHandThumb2', 'y', -math.pi/2.5),
            ('mixamorigRightHandThumb3', 'y', -math.pi/2.5),
            ('mixamorigRightHand', 'z', math.pi/4),
            ('mixamorigRightHand', 'x', math.pi/18),
            ('mixamorigRightForeArm', 'z', math.pi/9),
            ('mixamorigLeftHandRing1', 'z', -math.pi/2),
            ('mixamorigLeftHandRing2', 'z', -math.pi/2),
            ('mixamorigLeftHandRing3', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky1', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky2', 'z', -math.pi/2),
            ('mixamorigLeftHandPinky3', 'z', -math.pi/2),
            ('mixamorigLeftHandThumb2', 'y', math.pi/2.5),
            ('mixamorigLeftHandThumb3', 'y', math.pi/2.5),
            ('mixamorigLeftHand', 'z', -math.pi/3),
            ('mixamorigLeftForeArm', 'z', -math.pi/9),
        ],
        [
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigLeftHandRing1', 'z', 0),
            ('mixamorigLeftHandRing2', 'z', 0),
            ('mixamorigLeftHandRing3', 'z', 0),
            ('mixamorigLeftHandPinky1', 'z', 0),
            ('mixamorigLeftHandPinky2', 'z', 0),
            ('mixamorigLeftHandPinky3', 'z', 0),
            ('mixamorigLeftHandThumb2', 'y', 0),
            ('mixamorigLeftHandThumb3', 'y', 0),
            ('mixamorigLeftHand', 'z', 0),
            ('mixamorigLeftForeArm', 'z', 0),
        ],
    ]
