import math

def get_animation():
    return [
        [
            ('mixamorigRightHandIndex1', 'z', math.pi/2),
            ('mixamorigRightHandIndex2', 'z', math.pi/3),
            ('mixamorigRightHandIndex3', 'z', math.pi/3),
            ('mixamorigRightHandMiddle1', 'z', math.pi/2),
            ('mixamorigRightHandMiddle2', 'z', math.pi/3),
            ('mixamorigRightHandMiddle3', 'z', math.pi/3),
            ('mixamorigRightHandRing1', 'z', math.pi/2),
            ('mixamorigRightHandRing2', 'z', math.pi/3),
            ('mixamorigRightHandRing3', 'z', math.pi/3),
            ('mixamorigRightHandPinky1', 'z', -math.pi/4),
            ('mixamorigRightHandPinky2', 'z', math.pi/3),
            ('mixamorigRightHandPinky3', 'z', math.pi/3),
            ('mixamorigRightHandThumb2', 'y', -math.pi/2.5),
            ('mixamorigRightHandThumb3', 'y', -math.pi/2.5),
            ('mixamorigRightHand', 'y', math.pi/6),
            ('mixamorigRightHand', 'x', math.pi/3),
            ('mixamorigRightHand', 'z', -math.pi/6),
            ('mixamorigRightForeArm', 'z', math.pi/6),
            ('mixamorigRightArm', 'y', math.pi/33),
            ('mixamorigRightArm', 'z', math.pi/2.6),
            ('mixamorigLeftHandIndex1', 'z', -math.pi/1.6),
            ('mixamorigLeftHandIndex2', 'z', -math.pi/3),
            ('mixamorigLeftHandIndex3', 'z', -math.pi/3),
            ('mixamorigLeftHandMiddle1', 'z', -math.pi/1.6),
            ('mixamorigLeftHandMiddle2', 'z', -math.pi/3),
            ('mixamorigLeftHandMiddle3', 'z', -math.pi/3),
            ('mixamorigLeftHandRing1', 'z', -math.pi/1.6),
            ('mixamorigLeftHandRing2', 'z', -math.pi/3),
            ('mixamorigLeftHandRing3', 'z', -math.pi/3),
            ('mixamorigLeftHandPinky1', 'z', math.pi/4),
            ('mixamorigLeftHandPinky2', 'z', -math.pi/3),
            ('mixamorigLeftHandPinky3', 'z', -math.pi/3),
            ('mixamorigLeftHandThumb2', 'y', math.pi/2.5),
            ('mixamorigLeftHandThumb3', 'y', math.pi/2.5),
            ('mixamorigLeftHand', 'z', -math.pi/10),
            ('mixamorigLeftHand', 'x', -math.pi/6),
            ('mixamorigLeftForeArm', 'z', math.pi/6),
            ('mixamorigLeftForeArm', 'x', math.pi/2.7),
            ('mixamorigLeftForeArm', 'y', -math.pi*0.75),
            ('mixamorigLeftArm', 'z', -math.pi/2.6),
        ],
        [
            ('mixamorigRightHandIndex1', 'z', 0),
            ('mixamorigRightHandIndex2', 'z', 0),
            ('mixamorigRightHandIndex3', 'z', 0),
            ('mixamorigRightHandMiddle1', 'z', 0),
            ('mixamorigRightHandMiddle2', 'z', 0),
            ('mixamorigRightHandMiddle3', 'z', 0),
            ('mixamorigRightHandRing1', 'z', 0),
            ('mixamorigRightHandRing2', 'z', 0),
            ('mixamorigRightHandRing3', 'z', 0),
            ('mixamorigRightHandPinky1', 'z', 0),
            ('mixamorigRightHandPinky2', 'z', 0),
            ('mixamorigRightHandPinky3', 'z', 0),
            ('mixamorigRightHandThumb2', 'y', 0),
            ('mixamorigRightHandThumb3', 'y', 0),
            ('mixamorigRightHand', 'y', 0),
            ('mixamorigRightHand', 'x', 0),
            ('mixamorigRightHand', 'z', 0),
            ('mixamorigRightForeArm', 'z', 0),
            ('mixamorigRightArm', 'y', 0),
            ('mixamorigRightArm', 'z', 1.0471975511965976),
            ('mixamorigLeftHandIndex1', 'z', 0),
            ('mixamorigLeftHandIndex2', 'z', 0),
            ('mixamorigLeftHandIndex3', 'z', 0),
            ('mixamorigLeftHandMiddle1', 'z', 0),
            ('mixamorigLeftHandMiddle2', 'z', 0),
            ('mixamorigLeftHandMiddle3', 'z', 0),
            ('mixamorigLeftHandRing1', 'z', 0),
            ('mixamorigLeftHandRing2', 'z', 0),
            ('mixamorigLeftHandRing3', 'z', 0),
            ('mixamorigLeftHandPinky1', 'z', 0),
            ('mixamorigLeftHandPinky2', 'z', 0),
            ('mixamorigLeftHandPinky3', 'z', 0),
            ('mixamorigLeftHandThumb2', 'y', 0),
            ('mixamorigLeftHandThumb3', 'y', 0),
            ('mixamorigLeftHand', 'z', 0),
            ('mixamorigLeftHand', 'x', 0),
            ('mixamorigLeftForeArm', 'z', 0),
            ('mixamorigLeftForeArm', 'x', 0),
            ('mixamorigLeftForeArm', 'y', -2.0943951023931953),
            ('mixamorigLeftArm', 'z', -1.0471975511965976),
        ],
    ]
